### ISSUE TITLE
hashicorp/local v2.2.0: archive has incorrect checksum

### ISSUE THREAD

**Issue by skjensen** [hashicorp/terraform-provider-local#110]
### Terraform CLI and Provider Versions

Terraform v1.0.11
on linux_amd64

### Terraform Configuration

```terraform
n/a
```

### Expected Behavior

expected zh:f427480d3ec953434eccf21544b0b2be63595634e4e79a53575ceb892f22230d)

### Actual Behavior

Error while installing hashicorp/local v2.2.0: archive has incorrect checksum zh:507776b1e1901fdd6450a88298fc87a27a508e0c01405c7e8e8f2037d5963afe

### Steps to Reproduce

terraform init

### How much impact is this issue causing?

High

### Additional Information

- Installing hashicorp/local v2.2.0...
╷
│ Error: Failed to install provider
│ 
│ Error while installing hashicorp/local v2.2.0: archive has incorrect checksum zh:507776b1e1901fdd6450a88298fc87a27a508e0c01405c7e8e8f2037d5963afe (expected zh:f427480d3ec953434eccf21544b0b2be63595634e4e79a53575ceb892f22230d)
╵

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by spliskamatyshak** [comment]
Having the exact same issue on ubuntu 18.04 (LTS).

**Comment by Strakeln** [comment]
This issue has set a lot of things on fire in my workplace!

**Comment by amossc** [comment]
Duplicated by https://github.com/hashicorp/terraform-provider-local/issues/111 (but they have double the votes, so better merged into there)

**Comment by bflad** [comment]
Hi folks 👋  Thank you for reporting this and apologies for the unexpected 2.2.0 release issue. A new 2.2.1 release has been published to releases.hashicorp.com and the public Terraform Registry. Can you confirm that the new release is working as expected?

**Comment by tristanmorgan** [comment]
I ran `$ terraform providers lock -platform=darwin_amd64 -platform=darwin_arm64 -platform=linux_amd64 -platform=linux_arm64` and it worked fine for the target platforms (local provider updated to 2.2.1).

**Comment by Strakeln** [comment]
Seems to be working fine now. Thx!

**Comment by skjensen** [comment]
Confirmed it's working now with v2.2.1
