### ISSUE TITLE
Output property of generated file for local_file resource

### ISSUE THREAD

**Issue by jack-parsons-bjss** [hashicorp/terraform-provider-local#140]
### Terraform CLI and Provider Versions

```$ terraform version
Terraform v1.2.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v4.29.0
+ provider registry.terraform.io/hashicorp/local v2.2.3
```

### Use Cases or Problem Statement

We appear to be unable to depend on the output of this resource; we are trying to use this to generate a file from some content we pass in to create an AWS Lambda function. The Lambda resource is throwing errors that the file location does not exist on the disk, even after apparently data sourcing the local file resource:

```│ Error: Error in function call
│ 
│   on ../../modules/lambdacron/lambda_function.tf line 33, in resource "aws_lambda_function" "main":
│   33:         filebase64sha256(var.function_zip_base64 == null ? local.archive_path : data.local_file.archive[0].filename) :
│     ├────────────────
│     │ data.local_file.archive[0].filename is "./work/bjss-494849242700-eu-west-2-prod-granted-lambdacron-idp-sync/function.zip"
│     │ local.archive_path is "./work/bjss-494849242700-eu-west-2-prod-granted-lambdacron-idp-sync/function.zip"
│     │ var.function_zip_base64 is "UEsDBAoAAAAAAI97KFUQIvvVBQAAAAUAAAAIABwAaW5kZXguanNVVAkAAw78GWMO/BljdXgLAAEE6AMAAARkAAAAZXhpdApQSwECHgMKAAAAAACPeyhVECL71QUAAAAFAAAACAAYAAAAAAABAAAApIEAAAAAaW5kZXguanNVVAUAAw78GWN1eAsAAQToAwAABGQAAABQSwUGAAAAAAEAAQBOAAAARwAAAAAA"
│ 
│ Call to function "filebase64sha256" failed: open work/bjss-494849242700-eu-west-2-prod-granted-lambdacron-idp-sync/function.zip: no such file or directory.
╵
```

### Proposal

Output an attribute of the generated file - the octal permissions perhaps, or a file hash - which would allow us to depend on the attribute without needing to duplicate the content of the file in the output.

### How much impact is this issue causing?

Low

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tristanmorgan** [comment]
#142 looks like it would solve this too.

**Comment by bflad** [comment]
Hi @jack-parsons-bjss 👋 Thank you for raising this. As @tristanmorgan mentions above, recent versions of the `local_file` data source and resource now include additional attributes containing hashes of file contents. This is the correct and expected method for getting those values. Built-in Terraform configuration functions, such as file handling ones, only operate during configuration parsing rather than participating in the graph.
