### ISSUE TITLE
Default file permission misleading

### ISSUE THREAD

**Issue by tibeer** [hashicorp/terraform-provider-local#147]
### Terraform CLI and Provider Versions

Terraform v1.3.2
on darwin_arm64
+ provider registry.terraform.io/hashicorp/local v2.2.3

### Terraform Configuration

```terraform
resource "local_file" "dummy_file" {
  content  = "foobar"
  filename = "./dummy.txt"
}
```

### Expected Behavior

File is created according to the default value for attribute _file_permission_ (`0777`) which would mean:

```sh
tf@hashicorp example % ls -al dummy.txt
-rwxrwxrwx  1 tf  staff  6  8 Oct 16:02 dummy.txt
```

### Actual Behavior

File is created with the default umask permissions.

```sh
tf@hashicorp example % ls -al dummy.txt
-rwxr-xr-x  1 tf  staff  6  8 Oct 16:02 dummy.txt
```

### Steps to Reproduce

1. `terraform apply`
2. ls -al dummy.txt

### How much impact is this issue causing?

Low

### Additional Information

As per the documentation, if no _file_permission_ attribute is set, the default value would be used (`0777`). Happily this does not seem to be the case currently because it might be a security issue. The same issue is present for _directory_permission_. Might also be that the documentation is misleading here or I am mistaken :)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by curx** [comment]
@tibeer what is the value of your `umask`?

**Comment by tibeer** [comment]
022
