### ISSUE TITLE
Destroy time provisioner ignored when replacing resource.

### ISSUE THREAD

**Issue by eliaoggian** [hashicorp/terraform-provider-local#16]
When updating the file content, the file resource gets replaced, but the destroy time provisioner is not executed.

### Terraform Version
+ Terraform v0.11.7
+ provider.local v1.1.0

### Affected Resource(s)
Please list the resources as a list, for example:
- local_file
- local_exec (provisioner)

### Terraform Configuration Files
```hcl
resource "local_file" "data" {
  count    = 2
  content  = "asd"
  filename = "data-${count.index}"

  lifecycle {
    create_before_destroy = "true"
  }

  provisioner "local-exec" {
    command = "echo 'CREATE'"
  }

  provisioner "local-exec" {
    command = "echo 'DELETE'"
    when    = "destroy"
  }
}

```

### Expected Behavior
I expect the destroy provisioner to be runned when destroying the old local_file resource.
(DELETE should be printed to stdout)

### Actual Behavior
The destroy provisioner is ignored.
(DELETE is not printed to stdout)

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. Edit **local_file.data.content** string
3. `terraform apply`

**Comment by tholu** [comment]
I have the same problem. Trying to make the consul running on a worker node leave before destruction. I taint the resource where I want to redeploy and run `terraform apply` then.

Before recreating the resource, and the destroy-time provisioner just does not run and thus the worker node does not properly leave consul.

This seems like a serious oversight or I am doing something wrong.

@radeksimko Have you find any solution for this?

**Comment by bflad** [comment]
Hi folks 👋 Thank you for reporting this issue and apologies for the delayed response. In Terraform, the `provisioner` functionality is fully managed by Terraform core and not individual providers. If you are still experiencing issues, I would ensure you are running the latest version of Terraform or finding/creating issues in the [Terraform core issue tracker](https://github.com/hashicorp/terraform/issues) where those maintainers can appropriately triage the issue.
