### ISSUE TITLE
data local_file should be able to specify that the content of the file is sensitive

### ISSUE THREAD

**Issue by diirib** [hashicorp/terraform-provider-local#36]
local_file data source shows the content of the file in plain text in the tfstate. When importing data from a local_file resource with sensitive_content, it should not be shown.

An option should be present when creating the data local_file, so it should be possible to specify that the content is sensitive.

Use-case: accessing an existing file with a secret with a data local_file would show its content in the tfstate.

**Comment by ghostsquad** [comment]
Any movement on this?
