### ISSUE TITLE
Unable to create a sensitive binary file

### ISSUE THREAD

**Issue by dinwath** [hashicorp/terraform-provider-local#43]
### Terraform Version
Terraform v0.12.24
+ provider.local v1.4.0

### Affected Resource(s)
- local/resource_local_file.go

### Terraform Configuration Files
```hcl
resource "local_file" "a_secret_binary_file" {
  sensitive_content    = file("./secrets/secret.zip")
  filename             = "./temp/secret.zip"
  file_permission      = "0700"
  directory_permission = "0700"
}
```
### Expected Behavior
File `secrets.zip` is correctly copied from `./secrets` dir to `./temp`

### Actual Behavior
Copy (obviously) fails because `secrets.zip` contains bytes that are invalid when interpreted as an UTF-8 string. However there is no binary-enabled counterpart of the  `sensitive_content` attribute, so the only solution would be use  `content_base64` attibute. This however would cause the content of the file to be outputted in diff, disclosing sensitive data

### Steps to Reproduce
1. `terraform apply`

### Humble opinion
I think it would be better to add support for a separate boolean attribute that specifies whether or not the resource should be treated as sensitive (and maybe then deprecate/drop `sensitive_content`) instead of having another doppleganger attribute like `sensitive_content_base64` 

### References
-  #17

**Comment by detro** [comment]
This has been resolved by https://github.com/hashicorp/terraform-provider-local/pull/106.

Please take a look at the [new `local_sensitive_file` resource](https://registry.terraform.io/providers/hashicorp/local/latest/docs/resources/sensitive_file) `.content_base64` attribute.

I'm going to close this but please re-open with more details if this still doesn't resolve this issue.

Thank you
