### ISSUE TITLE
Feature Request - Ability to append a local file

### ISSUE THREAD

**Issue by vikas027** [hashicorp/terraform-provider-local#46]
As of now, there is no [option](https://registry.terraform.io/providers/hashicorp/local/latest/docs/resources/file) to update a local file.

It would be good to have an option to append to an already created file.

Maybe something like this?

```hcl
resource local_file config {
  content = local.some_config
  filename = "./file-name"
  file_permission = "0644"
  append = true
}
```

**Comment by tristanmorgan** [comment]
The catch I see here is: what happens if you run apply several times? In the "config as code" space I would have to do a test to see if the data was already in the file before writing. A `not_if grep ...`

**Comment by vikas027** [comment]
yeah, true. Something similar to what Ansible does.

**Comment by kmoe** [comment]
Thanks for the FR. As @tristanmorgan indicates, this change is not compatible with Terraform's lifecycle model in which state is (ceteris paribus) a function of config and there should be no further diff following a successful `terraform apply`.
