### ISSUE TITLE
Provide a Data Source to write files at read/refresh time

### ISSUE THREAD

**Issue by WilliamABradley** [hashicorp/terraform-provider-local#47]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

```
Terraform v0.13.1
```

### Affected Resource(s)
Please list the resources as a list, for example:
- local_file
- data.local_file

With this local provider, I am unable to create a file during the refresh step, this is vital for a use case with Kubernetes where I am fetching the contents of a kubeconfig file from another Data Source (AWS Secrets Manager), and I need to create it as a file, so that the Kubernetes Provider can authenticate with the cluster and refresh Kubernetes Resources.

### Solution

A possible solution would be creating a new write data source, or updating the existing data source to write content, if provided.

```tf

data "aws_secretsmanager_secret" "secret" {
  name = "cluster/config"
}

data "aws_secretsmanager_secret_version" "secret_version" {
  secret_id     = data.aws_secretsmanager_secret.secret.id
}

data "local_file" "kubeconfig" {
  filename = abspath("temp/kubeconfig")
  sensitive_content = data.aws_secretsmanager_secret_version.secret_version.secret_string
  write = true
}

provider "kubernetes" {
  # Use data source exported path, so that we ensure that the file is created before we use evaluate any Kubernetes Resource.
  config_path = data.local_file.kubeconfig.path
}

resource "kubernetes_secret" "my_secret" {
  metadata {
    name      = "api"
    namespace = "default"
  }
  type = "Opaque"
  data = {
    api_key = local.api_key
  }
}
```

As a workaround, I am currently using a custom module that uses Node.js and an external data source to write file content during read, however, this has downsides, as it shows the sensitive content in Terraform Plans, it isn't very portable, etc.

<details>
  <summary>Workaround</summary>
  
  main.tf:
  ```tf
  variable "path" {
    type = string
  }

  variable "data" {
    type = string
  }

  data "external" "file_write" {
    working_dir = path.module
    program     = ["node", "configure.js"]
  
    query = {
      path = abspath(var.path)
      data = var.data
    }
  }
  ```

  configure.js:
  ```js
  #!/usr/bin/env node
  const fs = require("fs");
  const { dirname } = require("path");  

  // Get Input/Output.
  function getInput() {
      process.stdin.resume();
      process.stdin.setEncoding('utf8');
      let buffer = '';
      process.stdin.on('data', function (chunk) {
          buffer += chunk;
      });  

      return new Promise((resolve) => {
          process.stdin.on('end', function () {
              resolve(buffer);
          });
      });
  }
  function sendOutput(result) {
      process.stdout.write(result);
      process.stdout.write('\n');
  }  

  getInput().then(function (q) {
      const query = JSON.parse(q);
      const { path, data } = query;
      const result = {};  

      // Ensure directory exists.
      const directory = dirname(path);
      if (!fs.existsSync(directory)) {
          fs.mkdirSync(directory, { recursive: true });
      }  

      // Write Data.
      fs.writeFileSync(path, data);  

      sendOutput(JSON.stringify(result));
  }).catch(e => {
      console.error(e);
      process.exit(-1);
  });
  ```
</details>

**Comment by kmoe** [comment]
Writing files at read/refresh time is incompatible with the Terraform lifecycle model: `Read` must be read-only. This change is therefore not possible in any form that would fix the original issue.

The Kubernetes `provider` config block can be configured using attributes from the kubeconfig file. For example (not tested with data source, but it should work):

```hcl
locals {
    kube_config = yamldecode(file("~/.kube/config"))
}
provider "helm" {
    kubernetes {
        host = local.kube_config.clusters[1].cluster.server
        cluster_ca_certificate = base64decode(local.kube_config.clusters[1].cluster.certificate-authority-data)
        client_certificate = base64decode(local.kube_config.users[1].user.client-certificate-data)
        client_key = base64decode(local.kube_config.users[1].user.client-key-data)
    }
}
```

Please feel free to make use of [the community forum](https://discuss.hashicorp.com/c/terraform-core) for more assistance configuring the Kubernetes provider.
