### ISSUE TITLE
What is the default behavior if is no version is specified?

### ISSUE THREAD

**Issue by jonassteinberg1** [hashicorp/terraform-provider-local#52]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
0.12

### Affected Resource(s)
Please list the resources as a list, for example:
- provider configuration

### Issue

The documentation does not specify what the behavior is if no version is specified in the provider configuration and I cannot find it anywhere else.  It would be helpful to know this as we prefer running latest-by-default if possible.  Any insight would be greatly appreciated!

**Comment by kmoe** [comment]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.
